import React from "react";
import { Link } from "react-router-dom";
import { createPageUrl } from "@/utils";
import { ArrowLeft, HelpCircle, Mail, MessageSquare, FileText, Shield, Settings, AlertTriangle } from "lucide-react";

const FAQS = [
  { q: "How do I create an account?", a: "Click 'Create Account' on the landing page or 'Sign In' in the header. You can register with your email address. Once registered, you can set up your profile with a username, bio, and image from the Settings page." },
  { q: "How does AI moderation work?", a: "Every post is analysed before publication for toxicity, personal attacks, and constructiveness. The AI assigns a quality score and may warn or block content that violates Community Guidelines. All moderation decisions include an explanation." },
  { q: "Can I edit or delete my convs?", a: "You can delete your convs from the platform. Editing is planned for a future release. Deleted convs are permanently removed along with their associated analytics." },
  { q: "What is a Reconv?", a: "A Reconv is when you share someone else's conv to your own feed. You can add your thoughts or simply amplify the original argument. Reconvs appear alongside your original convs on your profile." },
  { q: "How are quality scores calculated?", a: "Quality scores (0-100) are generated by AI based on argument structure, evidence usage, logical coherence, and constructiveness. Higher scores indicate stronger, better-structured arguments." },
  { q: "How do I report content?", a: "If you see content that violates our Community Guidelines, contact moderation@convs.io with the conv or comment ID and a description of the issue." },
  { q: "Is my data private?", a: "Your profile, convs, and comments are public by default. Direct messages are private. We do not sell your data. See our Privacy Policy for full details." },
  { q: "How do I delete my account?", a: "Contact support@convs.io with your account email to request account deletion. We will remove your account and associated data within 30 days." },
];

const CONTACT = [
  { icon: Mail, label: "General Support", value: "support@convs.io", desc: "For account issues, bugs, and general questions" },
  { icon: Shield, label: "Moderation", value: "moderation@convs.io", desc: "Report content violations or appeal moderation decisions" },
  { icon: FileText, label: "Legal", value: "legal@convs.io", desc: "Privacy, terms, and legal inquiries" },
  { icon: AlertTriangle, label: "Security", value: "security@convs.io", desc: "Report security vulnerabilities" },
];

export default function Support() {
  return (
    <div className="min-h-screen" style={{ background: "var(--convs-bg)" }}>
      <div className="max-w-4xl mx-auto px-4 py-12">
        <Link to={createPageUrl("Landing")} className="inline-flex items-center gap-2 text-sm mb-8 hover:underline" style={{ color: "var(--convs-accent)" }}>
          <ArrowLeft className="w-4 h-4" /> Back to Home
        </Link>

        <div className="flex items-center gap-3 mb-4">
          <HelpCircle className="w-8 h-8" style={{ color: "var(--convs-accent)" }} />
          <h1 className="text-4xl md:text-5xl font-bold" style={{ color: "var(--convs-text)" }}>Support</h1>
        </div>
        <p className="text-lg mb-12 leading-relaxed" style={{ color: "var(--convs-text-secondary)" }}>
          Need help? Find answers to common questions or contact our team directly.
        </p>

        {/* FAQ */}
        <h2 className="text-2xl font-bold mb-5" style={{ color: "var(--convs-text)" }}>Frequently Asked Questions</h2>
        <div className="space-y-3 mb-12">
          {FAQS.map((faq, i) => (
            <details key={i} className="convs-card p-4 group cursor-pointer">
              <summary className="font-semibold text-sm list-none flex items-center justify-between" style={{ color: "var(--convs-text)" }}>
                {faq.q}
                <span className="text-[var(--convs-text-muted)] group-open:rotate-45 transition-transform text-lg">+</span>
              </summary>
              <p className="text-sm mt-3 leading-relaxed" style={{ color: "var(--convs-text-secondary)" }}>{faq.a}</p>
            </details>
          ))}
        </div>

        {/* Contact */}
        <h2 className="text-2xl font-bold mb-5" style={{ color: "var(--convs-text)" }}>Contact Us</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {CONTACT.map(c => (
            <div key={c.label} className="convs-card p-5">
              <div className="flex items-center gap-3 mb-2">
                <div className="w-9 h-9 rounded-lg flex items-center justify-center" style={{ background: "var(--convs-accent-light)" }}>
                  <c.icon className="w-4.5 h-4.5" style={{ color: "var(--convs-accent)" }} />
                </div>
                <h3 className="font-bold text-sm" style={{ color: "var(--convs-text)" }}>{c.label}</h3>
              </div>
              <p className="text-sm font-medium mb-1" style={{ color: "var(--convs-accent)" }}>{c.value}</p>
              <p className="text-xs" style={{ color: "var(--convs-text-muted)" }}>{c.desc}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}